/*
 * ultrasonic.h
 *
 *  Created on: 15 Oct 2022
 *      Author: world
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"


#define PORT_TRIG_ID PORTB_ID
#define PIN_TRIG_ID PIN5_ID

 void ULTRASONIC_init(void);

/*
 * Description :
 * send the trigger pulse to the ultrasonic sensor.
 */
void ULTRASONIC_trigger(void);

/*
 * Description :
 * Send the trigger pulse by the ULTRASONC_trigger function.
 * Start the measurement by the ICU.
 * Return the distance in cm.
 */
uint16 ULTRASONIC_readDistance(void);

/*
 * Description :
 * the call back function called by the icu.
 *  calculate the pulse time generated by the ultrasonic sensor.
 */
void ULTRASONIC_edgeProcessing(void);



#endif /* ULTRASONIC_H_ */
